/**
 * canvasAssetSchema.ts — Mandatory structured params per asset node type.
 *
 * Each asset-producing phase MUST emit these params. The save-v2 and nodes
 * routes validate against these schemas and REJECT (HTTP 400) any asset
 * node that is missing required fields.
 *
 * This enforces the "structured params are mandatory, not optional" contract.
 *
 * Schema keys mirror the manifest params written by pipeline phases
 * (see _manifest.py → write_manifest → params dict).
 *
 * Per-type optional fields are augmented from
 * ``schema/pipeline-field-map.yaml`` via ``frontend-zod-extensions.ts``
 * (generated by ``python schema/generate_mappings.py``).
 */

import { z } from "zod";
import { YAML_OPTIONAL_FIELDS } from "../../schema/generated/frontend-zod-extensions";

// ─── Universal required fields (all media-bearing nodes) ──────────
//
// 52-UAT gap#1(2026-08-22)存量宽容:kmc sync 直写 DB 的真实图普遍含无媒体/无配方
// 参数的节点(修前诊断回放:项目 1/2/2001/9999 load-v2 原图原样回发 save-v2 全 400,
// 缺失形态全为 undefined/null,零空串)。filePath 等必填字段 nullish 化 = 与本文件
// prompt/description 可选化同一先例("rejecting on full-graph save would break the
// UI for 689 pre-existing asset rows")。管线写入本就直写 DB 绕过 HTTP,此门真正拦的
// 只有 UI 回写——nullish 化不弱化任何管线强制;**字段在场时仍强制形状**(空串/
// 负数照旧 400,行为锁 scripts/canvas/verify-save-v2-legacy-asset.ts 双分支锁死)。
// 各类型配方字段基线仍由文件尾的同名 EXPECTED 常量声明(本计划零改动),import-
// from-dir 的 __incomplete 警告语义不变。

const universalRequired = {
  filePath: z.string().min(1, "filePath is required for media nodes").nullish(),
};

// ─── Per-type param schemas ───────────────────────────────────────
//
// These are the STRUCTURED PARAMS stored in node.data (not columns).
// The pipeline MUST fill them. Missing → HTTP 400.
//
// Each base schema is augmented with optional fields declared in
// ``pipeline-field-map.yaml`` (which is the single source of truth for
// structured fields across the Python backend, this schema, and the
// import-from-dir enum normalizers).

function withYamlOptional<T extends z.ZodObject<any>>(
  baseType: string,
  base: T,
): z.ZodObject<any> {
  const extras = YAML_OPTIONAL_FIELDS[baseType] || [];
  const existing = Object.keys(base.shape);
  const toAdd: Record<string, z.ZodTypeAny> = {};
  for (const f of extras) {
    if (existing.includes(f.key)) continue;
    toAdd[f.key] = f.zodType === "number" ? z.number().optional() : z.string().optional();
  }
  return Object.keys(toAdd).length ? base.extend(toAdd) : base;
}

export const assetDataSchemas: Record<string, z.ZodSchema> = {
  // ── Audio nodes (P10 voice, P10b bgm/sfx, P12 audio_stems) ──
  // 52-UAT gap#1:nullish 化(修前回放实证 9999 项目 72 个 sync 写入 audio 节点
  // 缺 shot_id/engine/duration_sec;在场时 min 形状仍强制)。
  audio: withYamlOptional("audio", z.object({
    ...universalRequired,
    shot_id: z.string().min(1, "audio node requires shot_id").nullish(),
    engine: z.string().min(1, "audio node requires engine (e.g. ChatTTS)").nullish(),
    duration_sec: z.number().min(0, "audio node requires duration_sec >= 0 (0 = engine did not report)").nullish(),
    // Optional but expected:
    text: z.string().optional(),
    clip_type: z.string().optional(),
    // Phase 58 recipe fields (optional, present-shape enforced; shapes mirror
    // flowgraph-v3 zod.ts generationParamsSchema — root zod v4, no cross-package
    // zod import, Pitfall 4):
    steps: z.number().optional(),
    cfg: z.number().optional(),
    quant: z.string().optional(),
    sageAttention: z.boolean().optional(),
    lora: z.array(z.object({ name: z.string(), strength: z.number() }).strict()).optional(),
  })),

  // ── Video nodes (P11 video_render, P12 master, P13 delivery) ──
  // 52-UAT gap#1:nullish 化(修前回放实证 2001 项目 15 个 video 节点四字段全缺;
  // 在场时 min 形状仍强制)。
  video: withYamlOptional("video", z.object({
    ...universalRequired,
    shot_id: z.string().min(1, "video node requires shot_id").nullish(),
    engine: z.string().min(1, "video node requires engine (e.g. ltx)").nullish(),
    duration_sec: z.number().min(0, "video node requires duration_sec >= 0 (0 = engine did not report)").nullish(),
    resolution: z.string().min(1, "video node requires resolution (e.g. 1280x704)").nullish(),
    // Optional but expected:
    codec: z.string().optional(),
    thumbnailUrl: z.string().optional(),
    // Phase 58 recipe fields (optional, present-shape enforced; shapes mirror
    // flowgraph-v3 zod.ts generationParamsSchema — root zod v4, no cross-package
    // zod import, Pitfall 4):
    steps: z.number().optional(),
    cfg: z.number().optional(),
    quant: z.string().optional(),
    sageAttention: z.boolean().optional(),
    lora: z.array(z.object({ name: z.string(), strength: z.number() }).strict()).optional(),
  })),

  // ── Asset nodes (P04 character, P07 scene) ──
  // 52-UAT gap#1:摘除 universalRequired 展开,filePath/label/assetType 三字段
  // nullish 化(修前回放实证 43+9+3 节点缺失;sum-* 摘要卡/文本资产无媒体)——
  // 与 prompt/description 可选化同一先例(见下)。在场时 min(1) 仍强制。
  asset: withYamlOptional("asset", z.object({
    filePath: z.string().min(1, "filePath is required for media nodes").nullish(),
    // P04 character turnaround
    // P07 scene image
    label: z.string().min(1, "asset node requires label").nullish(),
    // At least one of these must identify what kind of asset it is
    assetType: z.string().min(1, "asset node requires assetType (character|scene|prop)").nullish(),
    // Generation prompt or human-readable description.
    // Pipeline SHOULD fill at least one; UI falls back from prompt → description.
    // Kept optional because legacy data lacks both, and rejecting on full-graph
    // save would break the UI for 689 pre-existing asset rows.
    prompt: z.string().optional(),
    description: z.string().optional(),
    // Optional structured params:
    scene_id: z.string().optional(),
    views: z.array(z.string()).optional(),
    style_vector: z.string().optional(),
    turnaround_path: z.string().optional(),
    // Phase 58 recipe fields (optional, present-shape enforced; shapes mirror
    // flowgraph-v3 zod.ts generationParamsSchema — root zod v4, no cross-package
    // zod import, Pitfall 4):
    steps: z.number().optional(),
    cfg: z.number().optional(),
    quant: z.string().optional(),
    sageAttention: z.boolean().optional(),
    lora: z.array(z.object({ name: z.string(), strength: z.number() }).strict()).optional(),
  })),

  // ── Storyboard nodes (P09 shot_breakdown) ──
  // 52-UAT gap#1:shot_id/shot_type/duration_sec nullish 化(修前回放实证 9999
  // 40+1+1 节点缺失;kmc sync 分镜卡缺管线配方参数)。label 无缺失证据,维持必填。
  storyboard: withYamlOptional("storyboard", z.object({
    label: z.string().min(1, "storyboard node requires label"),
    shot_id: z.string().min(1, "storyboard node requires shot_id").nullish(),
    shot_type: z.string().min(1, "storyboard requires shot_type (e.g. WS, CU)").nullish(),
    duration_sec: z.number().min(0, "storyboard requires duration_sec >= 0 (0 = engine did not report)").nullish(),
    // The storyboard may not have a rendered image yet (pre-production)
    filePath: z.string().optional(),
    // Optional but expected structured params:
    scene_ref: z.string().optional(),
    // Phase 58 recipe fields (optional, present-shape enforced; shapes mirror
    // flowgraph-v3 zod.ts generationParamsSchema — root zod v4, no cross-package
    // zod import, Pitfall 4):
    steps: z.number().optional(),
    cfg: z.number().optional(),
    quant: z.string().optional(),
    sageAttention: z.boolean().optional(),
    lora: z.array(z.object({ name: z.string(), strength: z.number() }).strict()).optional(),
  })),

  // ── Script nodes (P01-P06, P13 delivery) ──
  // Script nodes carry text content, not media. They require a description.
  // 52-UAT gap#1:description nullish 化(修前回放实证 127 节点缺失——kmc sync 的
  // 剧本/大纲节点无 description);filePath 修 optional→nullish(2001 实证 3 节点
  // 显式 null 形态,optional() 不收 null)。label 无缺失证据,维持必填。
  script: withYamlOptional("script", z.object({
    label: z.string().min(1, "script node requires label"),
    description: z.string().min(1, "script node requires description").nullish(),
    // Optional:
    assetType: z.string().optional(),
    filePath: z.string().nullish(),
    score: z.any().optional(),
    content: z.string().optional(),
    // Phase 58 recipe fields (optional, present-shape enforced; shapes mirror
    // flowgraph-v3 zod.ts generationParamsSchema — root zod v4, no cross-package
    // zod import, Pitfall 4):
    steps: z.number().optional(),
    cfg: z.number().optional(),
    quant: z.string().optional(),
    sageAttention: z.boolean().optional(),
    lora: z.array(z.object({ name: z.string(), strength: z.number() }).strict()).optional(),
  })),
};

// Types that are structural (zones, phases) — no required params
const structuralTypes = new Set(["zone", "phase", "suggestion", "reference"]);

// Types that are optional metadata — no required params
const optionalTypes = new Set(["3d", "variant", "upscale", "face_restore"]);

/**
 * Validate a node's data against its type-specific schema.
 *
 * Returns null if valid, or an error message string if invalid.
 * Structural types (zone, phase) and optional types always pass.
 */
export function validateNodeData(
  nodeType: string,
  data: Record<string, any>,
): string | null {
  // Structural nodes — no validation needed
  if (structuralTypes.has(nodeType) || optionalTypes.has(nodeType)) {
    return null;
  }

  const schema = assetDataSchemas[nodeType];
  if (!schema) {
    // Unknown type — allow but warn
    return null;
  }

  const result = schema.safeParse(data);
  if (result.success) {
    return null;
  }

  // Format errors
  const messages = result.error.issues.map(
    (issue: any) => `${issue.path.join(".")}: ${issue.message}`,
  );
  return messages.join("; ");
}

/**
 * Validate all nodes in a graph. Returns array of errors (empty if all valid).
 * Only validates nodes that have a type-specific schema.
 */
export function validateGraphNodes(
  nodes: Array<{ type: string; id: string; data: Record<string, any> }>,
): Array<{ nodeId: string; errors: string }> {
  const errors: Array<{ nodeId: string; errors: string }> = [];

  for (const node of nodes) {
    const err = validateNodeData(node.type, node.data || {});
    if (err) {
      errors.push({ nodeId: node.id, errors: err });
    }
  }

  return errors;
}

/**
 * Baseline expected params per node type. Mirrors Phase 42's
 * MANIFEST_PARAM_SCHEMA from
 * kais-hermes-skills/skills/kais-movie-pipeline/pipeline/phases/_manifest.py:64-74.
 *
 * BASELINE ONLY — phase-specific adds (PHASE_REQUIRED_FIELDS in Python,
 * e.g. archetype/role for p04) are enforced source-side by Phase 42 and
 * intentionally omitted here to avoid over-flagging the 689 historical
 * rows that pre-date the v2.0 contract (Pitfall 3 in 44-RESEARCH.md).
 *
 * Consumed by `import-from-dir.ts` (Plan 02) to warn + stamp
 * `__incomplete` / `__missing_fields` when an incoming manifest node is
 * missing baseline fields, and by `scripts/canvas/verify-schema-roundtrip.ts`
 * (Plan 03) for documentation cross-reference.
 */
export const EXPECTED_PARAM_FIELDS_BY_TYPE: Record<string, string[]> = {
  video: ["shot_id", "engine", "duration_sec", "resolution"],
  audio: ["shot_id", "engine", "duration_sec"],
  storyboard: ["shot_id", "shot_type", "duration_sec"],
  asset: ["label"],
  script: ["label"],
  reference: [],
  zone: [],
  phase: [],
  suggestion: [],
};
