/**
 * canvasAssetSchema.ts — Mandatory structured params per asset node type.
 *
 * Each asset-producing phase MUST emit these params. The save-v2 and nodes
 * routes validate against these schemas and REJECT (HTTP 400) any asset
 * node that is missing required fields.
 *
 * This enforces the "structured params are mandatory, not optional" contract.
 *
 * Schema keys mirror the manifest params written by pipeline phases
 * (see _manifest.py → write_manifest → params dict).
 *
 * Per-type optional fields are augmented from
 * ``schema/pipeline-field-map.yaml`` via ``frontend-zod-extensions.ts``
 * (generated by ``python schema/generate_mappings.py``).
 */

import { z } from "zod";
import { YAML_OPTIONAL_FIELDS } from "../../schema/generated/frontend-zod-extensions";

// ─── Universal required fields (all media-bearing nodes) ──────────

const universalRequired = {
  filePath: z.string().min(1, "filePath is required for media nodes"),
};

// ─── Per-type param schemas ───────────────────────────────────────
//
// These are the STRUCTURED PARAMS stored in node.data (not columns).
// The pipeline MUST fill them. Missing → HTTP 400.
//
// Each base schema is augmented with optional fields declared in
// ``pipeline-field-map.yaml`` (which is the single source of truth for
// structured fields across the Python backend, this schema, and the
// import-from-dir enum normalizers).

function withYamlOptional<T extends z.ZodObject<any>>(
  baseType: string,
  base: T,
): z.ZodObject<any> {
  const extras = YAML_OPTIONAL_FIELDS[baseType] || [];
  const existing = Object.keys(base.shape);
  const toAdd: Record<string, z.ZodTypeAny> = {};
  for (const f of extras) {
    if (existing.includes(f.key)) continue;
    toAdd[f.key] = f.zodType === "number" ? z.number().optional() : z.string().optional();
  }
  return Object.keys(toAdd).length ? base.extend(toAdd) : base;
}

export const assetDataSchemas: Record<string, z.ZodSchema> = {
  // ── Audio nodes (P10 voice, P10b bgm/sfx, P12 audio_stems) ──
  audio: withYamlOptional("audio", z.object({
    ...universalRequired,
    shot_id: z.string().min(1, "audio node requires shot_id"),
    engine: z.string().min(1, "audio node requires engine (e.g. ChatTTS)"),
    duration_sec: z.number().positive("audio node requires duration_sec > 0"),
    // Optional but expected:
    text: z.string().optional(),
    clip_type: z.string().optional(),
  })),

  // ── Video nodes (P11 video_render, P12 master, P13 delivery) ──
  video: withYamlOptional("video", z.object({
    ...universalRequired,
    shot_id: z.string().min(1, "video node requires shot_id"),
    engine: z.string().min(1, "video node requires engine (e.g. ltx)"),
    duration_sec: z.number().positive("video node requires duration_sec > 0"),
    resolution: z.string().min(1, "video node requires resolution (e.g. 1280x704)"),
    // Optional but expected:
    codec: z.string().optional(),
    thumbnailUrl: z.string().optional(),
  })),

  // ── Asset nodes (P04 character, P07 scene) ──
  asset: withYamlOptional("asset", z.object({
    ...universalRequired,
    // P04 character turnaround
    // P07 scene image
    label: z.string().min(1, "asset node requires label"),
    // At least one of these must identify what kind of asset it is
    assetType: z.string().min(1, "asset node requires assetType (character|scene|prop)"),
    // Generation prompt or human-readable description.
    // Pipeline SHOULD fill at least one; UI falls back from prompt → description.
    // Kept optional because legacy data lacks both, and rejecting on full-graph
    // save would break the UI for 689 pre-existing asset rows.
    prompt: z.string().optional(),
    description: z.string().optional(),
    // Optional structured params:
    scene_id: z.string().optional(),
    views: z.array(z.string()).optional(),
    style_vector: z.string().optional(),
    turnaround_path: z.string().optional(),
  })),

  // ── Storyboard nodes (P09 shot_breakdown) ──
  storyboard: withYamlOptional("storyboard", z.object({
    label: z.string().min(1, "storyboard node requires label"),
    shot_id: z.string().min(1, "storyboard node requires shot_id"),
    shot_type: z.string().min(1, "storyboard requires shot_type (e.g. WS, CU)"),
    duration_sec: z.number().positive("storyboard requires duration_sec > 0"),
    // The storyboard may not have a rendered image yet (pre-production)
    filePath: z.string().optional(),
    // Optional but expected structured params:
    scene_ref: z.string().optional(),
  })),

  // ── Script nodes (P01-P06, P13 delivery) ──
  // Script nodes carry text content, not media. They require a description.
  script: withYamlOptional("script", z.object({
    label: z.string().min(1, "script node requires label"),
    description: z.string().min(1, "script node requires description"),
    // Optional:
    assetType: z.string().optional(),
    filePath: z.string().optional(),
    score: z.any().optional(),
    content: z.string().optional(),
  })),
};

// Types that are structural (zones, phases) — no required params
const structuralTypes = new Set(["zone", "phase", "suggestion", "reference"]);

// Types that are optional metadata — no required params
const optionalTypes = new Set(["3d", "variant", "upscale", "face_restore"]);

/**
 * Validate a node's data against its type-specific schema.
 *
 * Returns null if valid, or an error message string if invalid.
 * Structural types (zone, phase) and optional types always pass.
 */
export function validateNodeData(
  nodeType: string,
  data: Record<string, any>,
): string | null {
  // Structural nodes — no validation needed
  if (structuralTypes.has(nodeType) || optionalTypes.has(nodeType)) {
    return null;
  }

  const schema = assetDataSchemas[nodeType];
  if (!schema) {
    // Unknown type — allow but warn
    return null;
  }

  const result = schema.safeParse(data);
  if (result.success) {
    return null;
  }

  // Format errors
  const messages = result.error.issues.map(
    (issue: any) => `${issue.path.join(".")}: ${issue.message}`,
  );
  return messages.join("; ");
}

/**
 * Validate all nodes in a graph. Returns array of errors (empty if all valid).
 * Only validates nodes that have a type-specific schema.
 */
export function validateGraphNodes(
  nodes: Array<{ type: string; id: string; data: Record<string, any> }>,
): Array<{ nodeId: string; errors: string }> {
  const errors: Array<{ nodeId: string; errors: string }> = [];

  for (const node of nodes) {
    const err = validateNodeData(node.type, node.data || {});
    if (err) {
      errors.push({ nodeId: node.id, errors: err });
    }
  }

  return errors;
}

/**
 * Baseline expected params per node type. Mirrors Phase 42's
 * MANIFEST_PARAM_SCHEMA from
 * kais-hermes-skills/skills/kais-movie-pipeline/pipeline/phases/_manifest.py:64-74.
 *
 * BASELINE ONLY — phase-specific adds (PHASE_REQUIRED_FIELDS in Python,
 * e.g. archetype/role for p04) are enforced source-side by Phase 42 and
 * intentionally omitted here to avoid over-flagging the 689 historical
 * rows that pre-date the v2.0 contract (Pitfall 3 in 44-RESEARCH.md).
 *
 * Consumed by `import-from-dir.ts` (Plan 02) to warn + stamp
 * `__incomplete` / `__missing_fields` when an incoming manifest node is
 * missing baseline fields, and by `scripts/verify-schema-roundtrip.ts`
 * (Plan 03) for documentation cross-reference.
 */
export const EXPECTED_PARAM_FIELDS_BY_TYPE: Record<string, string[]> = {
  video: ["shot_id", "engine", "duration_sec", "resolution"],
  audio: ["shot_id", "engine", "duration_sec"],
  storyboard: ["shot_id", "shot_type", "duration_sec"],
  asset: ["label"],
  script: ["label"],
  reference: [],
  zone: [],
  phase: [],
  suggestion: [],
};
