#!/usr/bin/env tsx
/**
 * verify-phase-30.ts — Phase 30 (Plan 01 + Plan 02) verification runner.
 *
 * Project convention (Pitfalls B3): no vitest/jest. This standalone `tsx`
 * script follows the `scripts/verify-phase-29.ts` pattern:
 *   - a local `assert()` helper pushes to a `results` array
 *   - a `main()` async function sums pass/fail and exits 1 on any failure
 *   - `main().catch(err => process.exit(2))` on uncaught exception
 *
 * Phase 30 success criteria (from ROADMAP + plan):
 *   1. (SC #1) Empty-DB boot → GET /api/v1/skills returns [movie-v1] summary.
 *   2. (SC #2) POST /register valid → 201, persisted, cache updated, retrievable.
 *   3. (SC #3) POST /register malformed → 400 with structured errors, no mutation.
 *   4. (SC #4) GET /node-types + /phases return declared arrays verbatim.
 *   5. (SC #5) Manifest derived from constants (spot-check 3 phases).
 *
 * Also closes API-01..API-05 (API-06 closed by Plan 30-01's boot wiring).
 *
 * Pitfalls B5 (ESM/CJS interop): the runner is invoked via
 * `tsx scripts/verify-phase-30.ts`. It is a standalone .ts file — NOT `tsx -e`.
 *
 * IMPORTANT SIDE-EFFECT NOTE:
 * The 5 route files (list/get/register/node-types/phases) import dependencies
 * that transitively reach `@/utils` → `@/utils/db.ts`, whose module body runs
 * an IIFE that initializes db2.sqlite + runs migrations + seeds movie-v1.
 * This means importing the route files triggers the real boot path. Two
 * consequences:
 *
 *   1. The singleton `u.db` is initialized at module load. Test 5 (malformed
 *      register) invokes the real register handler via Express — but since
 *      validateManifest fails BEFORE any `u.db(...)` call, the singleton db
 *      is never touched by the malformed test path.
 *
 *   2. movie-v1 may already be in the registry cache by the time main() runs,
 *      because seedDefaultIfEmpty ran as part of the @/utils/db IIFE.
 *      Test assertions are written to be order-independent for this reason
 *      (e.g., list length is checked `>= 1`, not `=== 1`).
 *
 * Test 6 (valid register) uses Option A (indirect) — it does NOT invoke the
 * real register handler (which would call the singleton db). It replicates
 * the handler's flow against a transient :memory: Knex instance. This keeps
 * the valid-register test hermetic.
 *
 * Usage:
 *   tsx scripts/verify-phase-30.ts
 *
 * Exit codes:
 *   0 — all assertions pass
 *   1 — one or more assertions failed (structured detail logged)
 *   2 — uncaught exception (test infrastructure bug)
 */

import knex from "knex";
import express from "express";
import type { Request, Response } from "express";
import { registry } from "../src/skills/registry";
import { validateManifest } from "../src/skills/validator";
import { seedDefaultIfEmpty, MOVIE_V1_MANIFEST } from "../src/skills/defaultSkill";
// Phase 31 inlined the pipeline callback constants into MOVIE_V1_MANIFEST as
// a literal phase_taxonomy[]. This verifier now reads expected values from
// literals / the manifest itself instead of importing the (now-deleted)
// constants from the pipeline callback layer.
// Importing the route files triggers @/utils/db's IIFE (see header note).
// This is accepted — see "IMPORTANT SIDE-EFFECT NOTE" above.
import listRoute from "../src/routes/v1/skills/list";
import getRoute from "../src/routes/v1/skills/get";
import registerRoute from "../src/routes/v1/skills/register";
import nodeTypesRoute from "../src/routes/v1/skills/node-types";
import phasesRoute from "../src/routes/v1/skills/phases";
import type { SkillManifest } from "../src/skills/contract";

interface TestResult {
  name: string;
  pass: boolean;
  detail?: string;
}

const results: TestResult[] = [];

function assert(cond: boolean, name: string, detail?: string): void {
  results.push({ name, pass: cond, detail });
  console.log(`  ${cond ? "PASS" : "FAIL"}: ${name}${detail ? " — " + detail : ""}`);
}

// ---------------------------------------------------------------------------
// Fixture builders
// ---------------------------------------------------------------------------

/**
 * Build a valid SkillManifest with the given skill_id. Mirrors the
 * verify-phase-29.ts fixture shape. Defensive: validates before returning so
 * fixture drift fails loudly here, not in the middle of a test.
 */
function buildValidManifest(skillId: string, nodeTypeBare: string): SkillManifest {
  const manifest: SkillManifest = {
    skill_id: skillId,
    version: "1.0",
    display_name: `Test Skill ${skillId}`,
    description: `Manifest fixture for ${skillId} — generated by verify-phase-30.ts`,
    media_types: ["video", "image"],
    node_types: [
      {
        type: `${skillId}::${nodeTypeBare}`,
        label: `Node ${nodeTypeBare}`,
        icon: "test-icon",
        color: "#000000",
        data_schema_uri: "https://example.com/schema.json",
        default_renderer: "script",
      },
    ],
    phase_taxonomy: [
      {
        id: "test-phase",
        order: 0,
        label: "Test Phase",
        requires_review: false,
        ingest_outputs: ["images"],
      },
    ],
    asset_categories: [{ id: "character-image", label: "Character Image" }],
    review_criteria: { auto_threshold: 0.8, human_threshold: 0.6 },
    engine_task_types: ["IMAGE_DRAW"],
    runtime: { type: "external-http", endpoint: "http://example.com" },
  };
  const check = validateManifest(manifest);
  if (!check.ok) {
    throw new Error(
      `verify-phase-30: fixture for ${skillId} is not a valid manifest — ` +
        `${check.errors[0]?.ruleId}: ${check.errors[0]?.message}`,
    );
  }
  return manifest;
}

/**
 * Build a manifest that fails NODE_ID_NAMESPACING — bare node type "script"
 * without the `<skill_id>::` prefix. Mirrors verify-phase-29.ts Test 5.
 */
function buildMalformedManifest(skillId: string): unknown {
  return {
    skill_id: skillId,
    version: "1.0",
    display_name: `Bad Skill ${skillId}`,
    description: "should be rejected — bare node type id",
    media_types: ["video"],
    node_types: [
      {
        type: "script", // bare — missing <skill_id>:: prefix → NODE_ID_NAMESPACING
        label: "Script",
        icon: "x",
        color: "#fff",
        data_schema_uri: "x",
        default_renderer: "script",
      },
    ],
    phase_taxonomy: [
      { id: "p1", order: 0, label: "P", requires_review: false, ingest_outputs: ["none"] },
    ],
    asset_categories: [{ id: "a", label: "A" }],
    review_criteria: { auto_threshold: 0.5, human_threshold: 0.3 },
    engine_task_types: ["IMAGE_DRAW"],
    runtime: { type: "in-process" },
  };
}

// ---------------------------------------------------------------------------
// HTTP helper — spin up Express on ephemeral port, return fetch base URL
// ---------------------------------------------------------------------------

async function withApp<T>(
  fn: (base: string) => Promise<T>,
): Promise<T> {
  // Mount routes in the SAME ORDER as src/router.ts (literal /register before
  // parameterized /:skillId). This mirrors production routing exactly.
  const app = express();
  app.use(express.json());
  app.use("/api/v1/skills", listRoute);
  app.use("/api/v1/skills/register", registerRoute); // literal FIRST
  app.use("/api/v1/skills/:skillId", getRoute);
  app.use("/api/v1/skills/:skillId", nodeTypesRoute);
  app.use("/api/v1/skills/:skillId", phasesRoute);

  return new Promise<T>((resolve, reject) => {
    const server = app.listen(0, () => {
      const addr = server.address();
      if (typeof addr !== "object" || addr === null) {
        server.close();
        reject(new Error("failed to listen on ephemeral port"));
        return;
      }
      const base = `http://127.0.0.1:${addr.port}`;
      fn(base)
        .then((v) => {
          server.close(() => resolve(v));
        })
        .catch((err) => {
          server.close(() => reject(err));
        });
    });
  });
}

// ---------------------------------------------------------------------------
// Main test driver
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("=== Phase 30 — verify-phase-30.ts ===");

  // -------------------------------------------------------------------------
  // Setup: transient :memory: SQLite Knex. Never touches db2.sqlite.
  // -------------------------------------------------------------------------
  const transientDb = knex({
    client: "better-sqlite3",
    connection: { filename: ":memory:" },
    useNullAsDefault: true,
  });

  // Create o_skillRegistry inline (mirror verify-phase-29.ts schema).
  await transientDb.schema.createTable("o_skillRegistry", (t) => {
    t.text("skill_id").notNullable();
    t.text("manifest_json");
    t.text("version");
    t.integer("active").defaultTo(1);
    t.integer("registered_at");
    t.primary(["skill_id"]);
  });

  // -------------------------------------------------------------------------
  // Test 1 — seedDefaultIfEmpty + manifest derivation (SC #1, #5, API-06)
  // -------------------------------------------------------------------------
  console.log("\n[Test 1] seedDefaultIfEmpty + manifest derivation");

  // 1a. Seed against fresh empty table — returns true, inserts one row.
  const seeded = await seedDefaultIfEmpty(transientDb);
  assert(seeded === true, "seed: empty-DB returns true", `returned=${seeded}`);

  // 1b. movie-v1 is in the registry cache.
  assert(
    registry.get("movie-v1")?.skill_id === "movie-v1",
    "seed: registry.get('movie-v1') returns the manifest after seed",
  );
  assert(
    registry.list().find((m) => m.skill_id === "movie-v1") !== undefined,
    "seed: registry.list() includes movie-v1",
  );

  // 1c. DB row exists.
  const movieRow = await transientDb("o_skillRegistry").where({ skill_id: "movie-v1" }).first();
  assert(movieRow != null, "seed: o_skillRegistry row for movie-v1 exists");
  assert(
    movieRow?.version === "1.0",
    "seed: row.version === '1.0'",
    `version=${movieRow?.version}`,
  );
  assert(
    movieRow?.active === 1,
    "seed: row.active === 1",
    `active=${movieRow?.active}`,
  );

  // 1d. Manifest's phase_taxonomy has exactly 12 phases in canonical order.
  // Phase 31 inlined the constant values into MOVIE_V1_MANIFEST directly, so
  // this assertion now locks the canonical 12-phase list + order against the
  // manifest literal (regression guard against accidental phase reordering).
  const manifest = MOVIE_V1_MANIFEST;
  const phaseIds = manifest.phase_taxonomy.map((p) => p.id);
  const expectedPhaseIds = [
    "requirement",
    "art-direction",
    "character",
    "scenario",
    "voice",
    "storyboard",
    "scene",
    "camera-preview",
    "camera-final",
    "post-production",
    "quality-gate",
    "delivery",
  ];
  assert(
    manifest.phase_taxonomy.length === 12,
    "manifest: phase_taxonomy has exactly 12 phases",
    `length=${manifest.phase_taxonomy.length}`,
  );
  assert(
    JSON.stringify(phaseIds) === JSON.stringify(expectedPhaseIds),
    "manifest: phase_taxonomy[].id list matches canonical 12-phase order exactly",
    `ids=${phaseIds.join(",")}`,
  );

  // 1e. Spot-check 3 phases against expected literals (SC #5 regression guard).
  //   - storyboard: review required, ingest ["storyboard"], order 5
  //   - scenario: no review, ingest []→["none"], order 3
  //   - art-direction: no review, ingest ["images"], order 1
  // Phase 31 inlined the constants into the manifest; expected values are now
  // literal booleans / numbers (previously derived from the deleted constants).
  const sb = manifest.phase_taxonomy.find((p) => p.id === "storyboard");
  assert(sb != null, "spot-check: storyboard phase exists in manifest");
  assert(
    sb?.requires_review === true,
    "spot-check: storyboard.requires_review === true",
    `requires_review=${sb?.requires_review}`,
  );
  assert(
    JSON.stringify(sb?.ingest_outputs) === JSON.stringify(["storyboard"]),
    "spot-check: storyboard.ingest_outputs === ['storyboard']",
    `ingest_outputs=${JSON.stringify(sb?.ingest_outputs)}`,
  );
  assert(
    sb?.order === 5,
    "spot-check: storyboard.order === 5",
    `order=${sb?.order}`,
  );

  const sc = manifest.phase_taxonomy.find((p) => p.id === "scenario");
  assert(sc != null, "spot-check: scenario phase exists in manifest");
  assert(
    sc?.requires_review === false,
    "spot-check: scenario.requires_review === false",
    `requires_review=${sc?.requires_review}`,
  );
  assert(
    JSON.stringify(sc?.ingest_outputs) === JSON.stringify(["none"]),
    "spot-check: scenario.ingest_outputs === ['none'] (empty array → ['none'] sentinel)",
    `ingest_outputs=${JSON.stringify(sc?.ingest_outputs)}`,
  );
  assert(
    sc?.order === 3,
    "spot-check: scenario.order === 3",
    `order=${sc?.order}`,
  );

  const ad = manifest.phase_taxonomy.find((p) => p.id === "art-direction");
  assert(ad != null, "spot-check: art-direction phase exists in manifest");
  assert(
    ad?.requires_review === false,
    "spot-check: art-direction.requires_review === false",
    `requires_review=${ad?.requires_review}`,
  );
  assert(
    JSON.stringify(ad?.ingest_outputs) === JSON.stringify(["images"]),
    "spot-check: art-direction.ingest_outputs === ['images']",
    `ingest_outputs=${JSON.stringify(ad?.ingest_outputs)}`,
  );
  assert(
    ad?.order === 1,
    "spot-check: art-direction.order === 1",
    `order=${ad?.order}`,
  );

  // 1f. Idempotency: re-seed on populated table returns false, no new row.
  const reSeedCountBefore = Number(
    (await transientDb("o_skillRegistry").count("* as c").first())?.c ?? 0,
  );
  const reSeeded = await seedDefaultIfEmpty(transientDb);
  const reSeedCountAfter = Number(
    (await transientDb("o_skillRegistry").count("* as c").first())?.c ?? 0,
  );
  assert(
    reSeeded === false,
    "seed: populated-DB returns false (idempotent no-op)",
    `returned=${reSeeded}`,
  );
  assert(
    reSeedCountAfter === reSeedCountBefore,
    "seed: idempotent call does not insert a duplicate row",
    `before=${reSeedCountBefore}, after=${reSeedCountAfter}`,
  );

  // -------------------------------------------------------------------------
  // Tests 2-5: HTTP endpoints via in-process Express app on ephemeral port.
  // -------------------------------------------------------------------------
  await withApp(async (base) => {
    // -------------------------------------------------------------------
    // Test 2 — GET /api/v1/skills (API-01, SC #1)
    // -------------------------------------------------------------------
    console.log("\n[Test 2] GET /api/v1/skills — summary list");

    const listResp = await fetch(`${base}/api/v1/skills`);
    const listBody = await listResp.json();
    assert(listResp.status === 200, "list: status 200", `status=${listResp.status}`);
    assert(listBody.ok === true, "list: body.ok === true");
    assert(Array.isArray(listBody.skills), "list: body.skills is an array");
    assert(listBody.skills.length >= 1, "list: at least one skill returned", `length=${listBody.skills.length}`);
    const movieSummary = listBody.skills.find((s: any) => s.skill_id === "movie-v1");
    assert(movieSummary != null, "list: skills[] contains movie-v1");

    // Summary has ONLY 4 keys + registered_at. Per API-01, summary shape is
    // {skill_id, version, display_name, description, registered_at}. Verify
    // no full-manifest leak (no node_types/phase_taxonomy/etc.).
    if (movieSummary) {
      const keys = Object.keys(movieSummary).sort();
      assert(
        JSON.stringify(keys) ===
          JSON.stringify(["description", "display_name", "registered_at", "skill_id", "version"]),
        "list: movie-v1 summary has EXACTLY {skill_id, version, display_name, description, registered_at} — no manifest leak",
        `keys=${keys.join(",")}`,
      );
      assert(
        typeof movieSummary.registered_at === "number",
        "list: movie-v1 summary.registered_at is a number",
        `typeof=${typeof movieSummary.registered_at}, value=${movieSummary.registered_at}`,
      );
    }

    // -------------------------------------------------------------------
    // Test 3 — GET /api/v1/skills/:skillId (API-02)
    // -------------------------------------------------------------------
    console.log("\n[Test 3] GET /api/v1/skills/:skillId — full manifest or 404");

    const getResp = await fetch(`${base}/api/v1/skills/movie-v1`);
    const getBody = await getResp.json();
    assert(getResp.status === 200, "get known: status 200", `status=${getResp.status}`);
    assert(getBody.ok === true, "get known: body.ok === true");
    assert(getBody.skill?.skill_id === "movie-v1", "get known: body.skill.skill_id === 'movie-v1'");
    assert(
      Array.isArray(getBody.skill?.phase_taxonomy) && getBody.skill.phase_taxonomy.length === 12,
      "get known: body.skill.phase_taxonomy is an array of 12",
      `length=${getBody.skill?.phase_taxonomy?.length}`,
    );

    const unknownResp = await fetch(`${base}/api/v1/skills/unknown-skill`);
    const unknownBody = await unknownResp.json();
    assert(unknownResp.status === 404, "get unknown: status 404", `status=${unknownResp.status}`);
    assert(unknownBody.ok === false, "get unknown: body.ok === false");
    assert(
      typeof unknownBody.error === "string" && unknownBody.error.includes("unknown-skill"),
      "get unknown: body.error contains 'unknown-skill'",
      `error=${unknownBody.error}`,
    );

    // -------------------------------------------------------------------
    // Test 4 — GET /api/v1/skills/:skillId/node-types + /phases (API-04, API-05, SC #4)
    // -------------------------------------------------------------------
    console.log("\n[Test 4] GET /node-types + /phases — declared arrays verbatim");

    const ntResp = await fetch(`${base}/api/v1/skills/movie-v1/node-types`);
    const ntBody = await ntResp.json();
    assert(ntResp.status === 200, "node-types known: status 200", `status=${ntResp.status}`);
    assert(ntBody.ok === true, "node-types known: body.ok === true");
    assert(
      Array.isArray(ntBody.node_types) && ntBody.node_types.length === 5,
      "node-types known: body.node_types is an array of 5",
      `length=${ntBody.node_types?.length}`,
    );
    // Spot-check: first node type's `type` is namespaced movie-v1::script.
    assert(
      ntBody.node_types?.some((n: any) => n.type === "movie-v1::script"),
      "node-types known: contains movie-v1::script",
    );

    const phResp = await fetch(`${base}/api/v1/skills/movie-v1/phases`);
    const phBody = await phResp.json();
    assert(phResp.status === 200, "phases known: status 200", `status=${phResp.status}`);
    assert(phBody.ok === true, "phases known: body.ok === true");
    assert(
      Array.isArray(phBody.phases) && phBody.phases.length === 12,
      "phases known: body.phases is an array of 12",
      `length=${phBody.phases?.length}`,
    );
    // Spot-check: phases include storyboard (declared, not derived).
    assert(
      phBody.phases?.some((p: any) => p.id === "storyboard"),
      "phases known: contains storyboard phase",
    );

    const ntUnknown = await fetch(`${base}/api/v1/skills/unknown-skill/node-types`);
    assert(ntUnknown.status === 404, "node-types unknown: status 404", `status=${ntUnknown.status}`);
    const ntUnknownBody = await ntUnknown.json();
    assert(
      ntUnknownBody.ok === false && typeof ntUnknownBody.error === "string",
      "node-types unknown: body.ok === false and body.error is a string",
    );

    const phUnknown = await fetch(`${base}/api/v1/skills/unknown-skill/phases`);
    assert(phUnknown.status === 404, "phases unknown: status 404", `status=${phUnknown.status}`);
    const phUnknownBody = await phUnknown.json();
    assert(
      phUnknownBody.ok === false && typeof phUnknownBody.error === "string",
      "phases unknown: body.ok === false and body.error is a string",
    );

    // -------------------------------------------------------------------
    // Test 5 — POST /api/v1/skills/register with malformed manifest (API-03 negative, SC #3)
    //
    // This invokes the REAL register handler via Express. validateManifest
    // fails BEFORE any DB call, so the singleton db2.sqlite is never touched.
    // -------------------------------------------------------------------
    console.log("\n[Test 5] POST /register malformed → 400 structured errors, no mutation");

    const malformed = buildMalformedManifest("bad-skill");
    const regBadResp = await fetch(`${base}/api/v1/skills/register`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(malformed),
    });
    const regBadBody = await regBadResp.json();
    assert(regBadResp.status === 400, "register malformed: status 400", `status=${regBadResp.status}`);
    assert(regBadBody.ok === false, "register malformed: body.ok === false");
    assert(
      Array.isArray(regBadBody.errors) && regBadBody.errors.length > 0,
      "register malformed: body.errors is a non-empty array",
      `length=${regBadBody.errors?.length}`,
    );
    assert(
      regBadBody.errors?.[0]?.ruleId === "NODE_ID_NAMESPACING",
      "register malformed: body.errors[0].ruleId === 'NODE_ID_NAMESPACING' (Phase 33 asserts on this)",
      `ruleId=${regBadBody.errors?.[0]?.ruleId}`,
    );

    // No mutation: bad-skill is not in the registry.
    assert(
      registry.get("bad-skill") === undefined,
      "register malformed: registry has no 'bad-skill' entry",
    );
    // No mutation: GET /bad-skill returns 404.
    const badGetResp = await fetch(`${base}/api/v1/skills/bad-skill`);
    assert(badGetResp.status === 404, "register malformed: GET /bad-skill returns 404", `status=${badGetResp.status}`);
  });

  // -------------------------------------------------------------------------
  // Test 6 — POST /api/v1/skills/register with valid manifest (API-03 positive, SC #2)
  //
  // Option A (indirect) — does NOT invoke the real register handler (which
  // would call the singleton db). Replicates the handler's three-step flow
  // against the transient :memory: DB: validate → UPSERT → registry.register.
  // -------------------------------------------------------------------------
  console.log("\n[Test 6] POST /register valid — round-trip proof (Option A indirect)");

  const validFixture = buildValidManifest("register-test-skill", "script");

  // 6a. validateManifest passes.
  const validResult = validateManifest(validFixture);
  assert(validResult.ok === true, "register valid: validateManifest(fixture).ok === true");

  // 6b. Replicate handler DB step against transient db (UPSERT).
  try {
    await transientDb("o_skillRegistry")
      .insert({
        skill_id: validFixture.skill_id,
        manifest_json: JSON.stringify(validFixture),
        version: validFixture.version,
        active: 1,
        registered_at: Date.now(),
      })
      .onConflict("skill_id")
      .merge();
    assert(true, "register valid: transientDb UPSERT succeeded");
  } catch (err) {
    assert(false, "register valid: transientDb UPSERT succeeded", (err as Error).message);
  }

  // 6c. Replicate handler cache step (registry.register).
  try {
    registry.register(validFixture);
    assert(true, "register valid: registry.register(fixture) succeeded");
  } catch (err) {
    assert(false, "register valid: registry.register(fixture) succeeded", (err as Error).message);
  }

  // 6d. Cache updated — registry.get returns the fixture.
  assert(
    registry.get("register-test-skill")?.skill_id === "register-test-skill",
    "register valid: registry.get('register-test-skill') returns the manifest (cache updated without restart)",
  );

  // 6e. DB row exists.
  const validRow = await transientDb("o_skillRegistry").where({ skill_id: "register-test-skill" }).first();
  assert(validRow != null, "register valid: o_skillRegistry row for register-test-skill exists");

  // 6f. Round-trip proof: GET /api/v1/skills/register-test-skill via in-process app → 200.
  await withApp(async (base) => {
    const roundTripResp = await fetch(`${base}/api/v1/skills/register-test-skill`);
    const roundTripBody = await roundTripResp.json();
    assert(
      roundTripResp.status === 200,
      "register valid: round-trip GET returns 200",
      `status=${roundTripResp.status}`,
    );
    assert(
      roundTripBody.skill?.skill_id === "register-test-skill",
      "register valid: round-trip GET body.skill.skill_id === 'register-test-skill'",
    );
  });

  // -------------------------------------------------------------------------
  // Teardown
  // -------------------------------------------------------------------------
  await transientDb.destroy();

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------
  const failed = results.filter((r) => !r.pass);
  console.log(
    `\n=== SUMMARY: ${results.length - failed.length} passed, ${failed.length} failed ===`,
  );

  if (failed.length > 0) {
    console.error("\nFAILED assertions:");
    for (const r of failed) {
      console.error(`  ✗ ${r.name}${r.detail ? " — " + r.detail : ""}`);
    }
    process.exit(1);
  }

  // Explicit exit 0 — required because importing the route files transitively
  // pulls in @/utils → @/utils/db.ts, whose Knex connection to db2.sqlite
  // holds the Node event loop open. Unlike verify-phase-29 (which imports
  // only from src/skills/* and exits naturally), this runner must force-exit.
  process.exit(0);
}

main().catch((err: unknown) => {
  console.error("verify-phase-30.ts: uncaught exception");
  console.error(err);
  process.exit(2);
});
