#!/usr/bin/env tsx
/**
 * verify-phase-29.ts — Phase 29 (Plan 01 + Plan 02) verification runner.
 *
 * Project convention (Pitfalls B3): no vitest/jest. This standalone `tsx`
 * script follows the `scripts/verify-phase-28.ts` pattern:
 *   - a local `assert()` helper pushes to a `results` array
 *   - a `main()` async function sums pass/fail and exits 1 on any failure
 *   - `main().catch(err => process.exit(2))` on uncaught exception
 *
 * Phase 29 success criteria (from ROADMAP + plan):
 *   1. Backfill: pre-existing NULL skill_id rows become "movie-v1"; orphaned
 *      assets are covered; non-NULL rows are untouched; workflow_phase column
 *      is added but NOT backfilled (stays NULL).
 *   2. Populated-table boot: loadAllFromDB registers every valid row, skips
 *      invalid ones, and builds secondary indexes so phaseById / nodeTypeById
 *      return the declared PhaseDecl / NodeTypeDecl.
 *   3. Empty-table boot: loadAllFromDB resolves with 0, registry.list()
 *      returns [], no crash.
 *   4. Registry lookups: known returns declared, unknown returns undefined
 *      (no fallback to movie-v1).
 *
 * Pitfalls B5 (ESM/CJS interop): the runner is invoked via `tsx
 * scripts/verify-phase-29.ts`. It does NOT import `src/lib/fixDB.ts` because
 * fixDB imports the singleton `db` from `@/utils/db`, which would initialize
 * the real db2.sqlite file. Likewise, it does NOT import
 * `src/lib/initDB.ts` because initDB transitively imports `getEmbedding`
 * from `@/utils/agent/embedding`, which in turn imports the singleton `db`.
 * Instead, the runner replicates BOTH the table creation (for the 3 tables
 * the tests touch: o_assets, kv_pipelineRun, o_skillRegistry) AND the 5
 * fixDB migration statements (3 addColumn + 2 backfill UPDATE) inline
 * against a transient `:memory:` Knex instance. This tests the migration
 * EFFECT, not the call sites — the call sites are exercised by real boot.
 *
 * Usage:
 *   tsx scripts/verify-phase-29.ts
 *
 * Exit codes:
 *   0 — all assertions pass
 *   1 — one or more assertions failed (the structured failure detail is logged)
 *   2 — uncaught exception (test infrastructure bug)
 */

import knex from "knex";
import { registry } from "../src/skills/registry";
import { loadAllFromDB } from "../src/skills/loader";
import { validateManifest } from "../src/skills/validator";
import type { SkillManifest } from "../src/skills/contract";

interface TestResult {
  name: string;
  pass: boolean;
  detail?: string;
}

const results: TestResult[] = [];

function assert(cond: boolean, name: string, detail?: string): void {
  results.push({ name, pass: cond, detail });
  console.log(`  ${cond ? "PASS" : "FAIL"}: ${name}${detail ? " — " + detail : ""}`);
}

// ---------------------------------------------------------------------------
// Fixture builders — produce SkillManifest objects that pass validateManifest().
// ---------------------------------------------------------------------------

/**
 * Build a valid SkillManifest with the given skill_id and concrete phase/node
 * type ids. Used by Tests 3 and 4. Every field is populated to satisfy the
 * strict zod schema; the node type `type` is properly namespaced
 * (`<skill_id>::<type>`) per Invariant 5.
 */
function buildValidManifest(
  skillId: string,
  phaseId: string,
  nodeTypeBare: string,
): SkillManifest {
  const manifest: SkillManifest = {
    skill_id: skillId,
    version: "1.0",
    display_name: `Test Skill ${skillId}`,
    description: `Manifest fixture for ${skillId} — generated by verify-phase-29.ts`,
    media_types: ["video", "image"],
    node_types: [
      {
        type: `${skillId}::${nodeTypeBare}`,
        label: `Node ${nodeTypeBare}`,
        icon: "test-icon",
        color: "#000000",
        data_schema_uri: "https://example.com/schema.json",
        default_renderer: "script",
      },
    ],
    phase_taxonomy: [
      {
        id: phaseId,
        order: 0,
        label: `Phase ${phaseId}`,
        requires_review: false,
        ingest_outputs: ["images"],
      },
    ],
    asset_categories: [{ id: "character-image", label: "Character Image" }],
    review_criteria: { auto_threshold: 0.8, human_threshold: 0.6 },
    engine_task_types: ["IMAGE_DRAW"],
    runtime: { type: "external-http", endpoint: "http://example.com" },
  };
  // Defensive: confirm the fixture passes validation before the test uses it.
  // This catches fixture drift early (e.g., a schema change that invalidates
  // the test fixture without the test author noticing).
  const check = validateManifest(manifest);
  if (!check.ok) {
    throw new Error(
      `verify-phase-29: fixture for ${skillId} is not a valid manifest — ` +
        `${check.errors[0]?.ruleId}: ${check.errors[0]?.message}`,
    );
  }
  return manifest;
}

// ---------------------------------------------------------------------------
// Main test driver
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("=== Phase 29 — verify-phase-29.ts ===");

  // -------------------------------------------------------------------------
  // Setup: transient :memory: SQLite Knex. Never touches db2.sqlite.
  // -------------------------------------------------------------------------
  const db = knex({
    client: "better-sqlite3",
    connection: { filename: ":memory:" },
    useNullAsDefault: true,
  });

  // Create the 3 tables the tests touch, inline. Do NOT import initDB —
  // initDB imports getEmbedding which imports the singleton db. The schemas
  // below mirror initDB.ts for these 3 tables (only the columns the tests
  // exercise; SQLite is permissive about extra columns).
  //   - o_assets: backfill test (Test 1)
  //   - kv_pipelineRun: backfill test (Test 1)
  //   - o_skillRegistry: loader test (Tests 2 + 3)
  await db.schema.createTable("o_assets", (t) => {
    t.integer("id").notNullable();
    t.integer("projectId");
    t.text("name");
    t.primary(["id"]);
  });
  await db.schema.createTable("kv_pipelineRun", (t) => {
    t.string("id").notNullable();
    t.integer("projectId").notNullable();
    t.primary(["id"]);
  });
  await db.schema.createTable("o_skillRegistry", (t) => {
    t.text("skill_id").notNullable();
    t.text("manifest_json");
    t.text("version");
    t.integer("active").defaultTo(1);
    t.integer("registered_at");
    t.primary(["skill_id"]);
  });

  // -------------------------------------------------------------------------
  // Test 1 — Backfill (Success Criterion 1)
  // -------------------------------------------------------------------------
  console.log("\n[Test 1] Backfill — pre-existing NULL skill_id rows become movie-v1");

  // Replicate the 3 addColumn statements from Plan 29-01 Task 2 inline.
  // Do NOT import fixDB — fixDB pulls the singleton db.
  await db.schema.alterTable("o_assets", (t) => (t as any).string("skill_id"));
  await db.schema.alterTable("o_assets", (t) => (t as any).string("workflow_phase"));
  await db.schema.alterTable("kv_pipelineRun", (t) => (t as any).string("skill_id"));

  // Seed 3 o_assets rows: one valid-project with NULL skill_id, one orphan
  // (projectId NULL) with NULL skill_id, one already set to "other-skill".
  await db("o_assets").insert([
    { id: 1001, projectId: 501, skill_id: null },
    { id: 1002, projectId: null, skill_id: null }, // orphan
    { id: 1003, projectId: 502, skill_id: "other-skill" },
  ]);
  // Seed 2 kv_pipelineRun rows with NULL skill_id.
  await db("kv_pipelineRun").insert([
    { id: "run-aaa", projectId: 501, skill_id: null },
    { id: "run-bbb", projectId: 502, skill_id: null },
  ]);

  // Run the backfill UPDATEs (identical to fixDB.ts lines 81-82).
  await db("o_assets").whereNull("skill_id").update({ skill_id: "movie-v1" });
  await db("kv_pipelineRun").whereNull("skill_id").update({ skill_id: "movie-v1" });

  // Assertions
  const nullAssets = await db("o_assets").whereNull("skill_id").count("* as c").first();
  const nullRuns = await db("kv_pipelineRun").whereNull("skill_id").count("* as c").first();
  const orphanRow = await db("o_assets").where("id", 1002).first();
  const otherSkillRow = await db("o_assets").where("id", 1003).first();

  assert(
    Number(nullAssets?.c) === 0,
    "backfill: no NULL skill_id remains in o_assets",
    `count=${nullAssets?.c}`,
  );
  assert(
    Number(nullRuns?.c) === 0,
    "backfill: no NULL skill_id remains in kv_pipelineRun",
    `count=${nullRuns?.c}`,
  );
  assert(
    orphanRow?.skill_id === "movie-v1",
    "backfill: orphaned asset (projectId NULL) is backfilled to movie-v1",
    `skill_id=${orphanRow?.skill_id}`,
  );
  assert(
    otherSkillRow?.skill_id === "other-skill",
    "backfill: non-NULL rows are not overwritten",
    `skill_id=${otherSkillRow?.skill_id}`,
  );

  // workflow_phase column exists and is NULL for every row (not backfilled).
  const wfPhaseRows = await db("o_assets").whereNotNull("workflow_phase").count("* as c").first();
  const hasWfPhaseColumn = await db.schema.hasColumn("o_assets", "workflow_phase");
  assert(hasWfPhaseColumn, "backfill: workflow_phase column was added to o_assets");
  assert(
    Number(wfPhaseRows?.c) === 0,
    "backfill: workflow_phase is NOT backfilled (remains NULL on every row)",
    `non-null count=${wfPhaseRows?.c}`,
  );

  // -------------------------------------------------------------------------
  // Test 2 — loadAllFromDB with empty table (Success Criterion 3)
  //
  // IMPORTANT (Warn 4 fix): runs BEFORE any registry.register() call so
  // registry.list().length === 0 can be asserted cleanly. The registry is a
  // non-clearable singleton; once register fires in Test 3, list() never
  // returns [] again within this process.
  // -------------------------------------------------------------------------
  console.log("\n[Test 2] Empty-table boot — loadAllFromDB returns 0, no crash");

  // The transient DB has o_skillRegistry created by initDB but no rows
  // (Plan 29-01 Task 1 explicitly omits initData for the table).
  let emptyThrew = false;
  let emptyCount = -1;
  try {
    emptyCount = await loadAllFromDB(db);
  } catch (err) {
    emptyThrew = true;
    console.error("  unexpected throw from loadAllFromDB on empty table:", err);
  }
  assert(emptyThrew === false, "loader: empty table does not throw");
  assert(emptyCount === 0, "loader: empty table returns 0 registered", `count=${emptyCount}`);
  assert(
    registry.list().length === 0,
    "loader: empty table leaves registry empty (Success Criterion #3 — list() returns [])",
    `length=${registry.list().length}`,
  );

  // -------------------------------------------------------------------------
  // Test 3 — loadAllFromDB with populated table (Success Criterion 2)
  // -------------------------------------------------------------------------
  console.log("\n[Test 3] Populated-table boot — valid row registered, invalid skipped");

  const validManifest = buildValidManifest(
    "loader-test-skill",
    "loader-phase-a",
    "script",
  );
  // Insert the valid manifest row.
  await db("o_skillRegistry").insert({
    skill_id: "loader-test-skill",
    manifest_json: JSON.stringify(validManifest),
    version: "1.0",
    active: 1,
    registered_at: Date.now(),
  });
  // Insert an INVALID manifest row (missing required fields, bad version).
  await db("o_skillRegistry").insert({
    skill_id: "loader-bad-skill",
    manifest_json: JSON.stringify({
      skill_id: "loader-bad-skill",
      version: "not-a-version", // fails MANIFEST_VERSION_FORMAT
      // missing many required fields — will also fail MANIFEST_REQUIRED_FIELD
    }),
    version: "not-a-version",
    active: 1,
    registered_at: Date.now(),
  });

  const count = await loadAllFromDB(db);

  assert(
    count === 1,
    "loader: populated table registers exactly the one valid row (invalid row skipped)",
    `count=${count}`,
  );
  assert(
    registry.get("loader-test-skill")?.skill_id === "loader-test-skill",
    "loader: valid row is in registry after load",
  );
  assert(
    registry.get("loader-bad-skill") === undefined,
    "loader: invalid row is skipped (not in registry)",
  );
  assert(
    registry.phaseById("loader-test-skill", "loader-phase-a")?.id === "loader-phase-a",
    "loader: secondary indexes built for loaded manifest — phaseById returns declared PhaseDecl",
  );
  assert(
    registry.nodeTypeById("loader-test-skill", "loader-test-skill::script")?.type ===
      "loader-test-skill::script",
    "loader: secondary indexes built for loaded manifest — nodeTypeById returns declared NodeTypeDecl",
  );

  // -------------------------------------------------------------------------
  // Test 4 — Registry known/unknown lookups (Success Criterion 4)
  // -------------------------------------------------------------------------
  console.log("\n[Test 4] Registry known/unknown lookups — no fallback to movie-v1");

  // Register a second manifest directly (additive — distinct skill_id).
  const secondManifest = buildValidManifest("test-skill-2", "phase-b", "storyboard");
  registry.register(secondManifest);

  assert(
    registry.get("test-skill-2")?.skill_id === "test-skill-2",
    "registry.get: known skill returns manifest",
  );
  assert(
    registry.get("unknown-skill") === undefined,
    "registry.get: unknown skill returns undefined (no fallback)",
  );
  assert(
    registry.phaseById("test-skill-2", "phase-b")?.id === "phase-b",
    "registry.phaseById: known phase returns PhaseDecl",
  );
  assert(
    registry.phaseById("test-skill-2", "unknown-phase") === undefined,
    "registry.phaseById: unknown phase returns undefined (no fallback)",
  );
  assert(
    registry.phaseById("unknown-skill", "phase-b") === undefined,
    "registry.phaseById: unknown skill returns undefined",
  );
  assert(
    registry.nodeTypeById("test-skill-2", "test-skill-2::storyboard")?.type ===
      "test-skill-2::storyboard",
    "registry.nodeTypeById: known type returns NodeTypeDecl",
  );
  assert(
    registry.nodeTypeById("test-skill-2", "unknown-type") === undefined,
    "registry.nodeTypeById: unknown type returns undefined",
  );
  assert(
    registry.list().length >= 2,
    "registry.list: returns at least the two registered skills",
    `length=${registry.list().length}`,
  );

  // -------------------------------------------------------------------------
  // Test 5 — register() rejects invalid manifest (Pitfalls A5 guard)
  // -------------------------------------------------------------------------
  console.log("\n[Test 5] register() rejects invalid manifest — throws, no corruption");

  // Invalid: bare node type "script" (not namespaced) — fails NODE_ID_NAMESPACING.
  const invalidManifest = {
    skill_id: "invalid-skill-id",
    version: "1.0",
    display_name: "Invalid",
    description: "should be rejected",
    media_types: ["video"],
    node_types: [
      {
        type: "script", // bare — missing <skill_id>:: prefix
        label: "Script",
        icon: "x",
        color: "#fff",
        data_schema_uri: "x",
        default_renderer: "script",
      },
    ],
    phase_taxonomy: [
      { id: "p1", order: 0, label: "P", requires_review: false, ingest_outputs: ["none"] },
    ],
    asset_categories: [{ id: "a", label: "A" }],
    review_criteria: { auto_threshold: 0.5, human_threshold: 0.3 },
    engine_task_types: ["IMAGE_DRAW"],
    runtime: { type: "in-process" },
  };

  let threw = false;
  try {
    registry.register(invalidManifest as any);
  } catch (err) {
    threw = true;
    console.log(`  → register threw: ${(err as Error).message}`);
  }
  assert(threw === true, "registry.register: invalid manifest throws (does not corrupt registry)");
  assert(
    registry.get("invalid-skill-id") === undefined,
    "registry.register: invalid manifest was not stored",
  );

  // -------------------------------------------------------------------------
  // Teardown
  // -------------------------------------------------------------------------
  await db.destroy();

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------
  const failed = results.filter((r) => !r.pass);
  console.log(
    `\n=== SUMMARY: ${results.length - failed.length} passed, ${failed.length} failed ===`,
  );

  if (failed.length > 0) {
    console.error("\nFAILED assertions:");
    for (const r of failed) {
      console.error(`  ✗ ${r.name}${r.detail ? " — " + r.detail : ""}`);
    }
    process.exit(1);
  }
}

main().catch((err: unknown) => {
  console.error("verify-phase-29.ts: uncaught exception");
  console.error(err);
  process.exit(2);
});
