// @routes-hash 24d8abdbad6cf26c437a09b30ae7dbee
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/addAudioAssets";
import route3 from "./routes/canvas/convert";
import route4 from "./routes/canvas/execute";
import route5 from "./routes/canvas/load";
import route6 from "./routes/canvas/orchestrate";
import route7 from "./routes/canvas/projectData";
import route8 from "./routes/canvas/projects";
import route9 from "./routes/canvas/review/approve";
import route10 from "./routes/canvas/review/reject";
import route11 from "./routes/canvas/review/score";
import route12 from "./routes/canvas/save";
import route13 from "./routes/canvas/storyboardPreview";
import route14 from "./routes/canvas/v2/branches";
import route15 from "./routes/canvas/v2/events";
import route16 from "./routes/canvas/v2/file";
import route17 from "./routes/canvas/v2/health";
import route18 from "./routes/canvas/v2/import-from-dir";
import route19 from "./routes/canvas/v2/layout";
import route20 from "./routes/canvas/v2/links";
import route21 from "./routes/canvas/v2/load-v2";
import route22 from "./routes/canvas/v2/nodes";
import route23 from "./routes/canvas/v2/review-gate";
import route24 from "./routes/canvas/v2/save-v2";
import route25 from "./routes/canvas/v2/thumbnail/batch";
import route26 from "./routes/canvas/v2/thumbnail/index";
import route27 from "./routes/production/flux/kontext-generate/index";
import route28 from "./routes/production/flux/sceneGenerate";
import route29 from "./routes/production/flux/status";
import route30 from "./routes/production/indextts2/speak";
import route31 from "./routes/production/indextts2/status";
import route32 from "./routes/production/ltx/extension";
import route33 from "./routes/production/ltx/fflf";
import route34 from "./routes/production/ltx/msr";
import route35 from "./routes/production/ltx/poseVideo";
import route36 from "./routes/production/ltx/promptRelayI2V";
import route37 from "./routes/production/ltx/singularityFFLF";
import route38 from "./routes/production/ltx/trim";
import route39 from "./routes/production/ltx/twoStageAudioI2V";
import route40 from "./routes/production/postprocess/enhance";
import route41 from "./routes/production/postprocess/status";
import route42 from "./routes/production/qwenTts/speak";
import route43 from "./routes/production/qwenTts/status";
import route44 from "./routes/production/qwenTts/voiceId";
import route45 from "./routes/production/storyboard/addStoryboard";
import route46 from "./routes/production/wan21/scail2/status";
import route47 from "./routes/production/wan21/scail2Replace";
import route48 from "./routes/production/wan21/scail2Transfer";
import route49 from "./routes/production/wan22/fflf";
import route50 from "./routes/production/wan22/i2v";
import route51 from "./routes/production/wan22/movetrack";
import route52 from "./routes/production/wan22/t2v";
import route53 from "./routes/project/addProject";
import route54 from "./routes/project/delProject";
import route55 from "./routes/project/editProject";
import route56 from "./routes/project/getProject";
import route57 from "./routes/proxy/goldTeam";
import route58 from "./routes/proxy/reviewPlatform";
import route59 from "./routes/script/addScript";
import route60 from "./routes/setting/agentDeploy/agentSetKey";
import route61 from "./routes/setting/agentDeploy/deployAgentModel";
import route62 from "./routes/setting/agentDeploy/getAgentDeploy";
import route63 from "./routes/setting/agentDeploy/getAgentUseMode";
import route64 from "./routes/setting/agentDeploy/updateUseMode";
import route65 from "./routes/setting/promptManage/getPrompt";
import route66 from "./routes/setting/promptManage/updatePrompt";
import route67 from "./routes/setting/skillManagement/getSkillContent";
import route68 from "./routes/setting/skillManagement/getSkillList";
import route69 from "./routes/setting/skillManagement/saveSkillContent";
import route70 from "./routes/setting/vendorConfig/addVendor";
import route71 from "./routes/setting/vendorConfig/addVendorModel";
import route72 from "./routes/setting/vendorConfig/deleteVendor";
import route73 from "./routes/setting/vendorConfig/delVendorModel";
import route74 from "./routes/setting/vendorConfig/enableVendor";
import route75 from "./routes/setting/vendorConfig/getCodeByLink";
import route76 from "./routes/setting/vendorConfig/getVendorList";
import route77 from "./routes/setting/vendorConfig/modelTest";
import route78 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route79 from "./routes/setting/vendorConfig/modelTest/textTest";
import route80 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route81 from "./routes/setting/vendorConfig/updateCode";
import route82 from "./routes/setting/vendorConfig/updateVendorInputs";
import route83 from "./routes/setting/vendorConfig/upVendorModel";
import route84 from "./routes/v1/ace/cancel";
import route85 from "./routes/v1/ace/comfyuiAnalyze";
import route86 from "./routes/v1/ace/comfyuiDownload";
import route87 from "./routes/v1/ace/comfyuiGenerate";
import route88 from "./routes/v1/ace/generate";
import route89 from "./routes/v1/ace/models";
import route90 from "./routes/v1/ace/profiles";
import route91 from "./routes/v1/ace/scheduler";
import route92 from "./routes/v1/ace/status";
import route93 from "./routes/v1/assets-registry/index";
import route94 from "./routes/v1/assets/from_node";
import route95 from "./routes/v1/audit/index";
import route96 from "./routes/v1/feedback/index";
import route97 from "./routes/v1/hunyuan3d/cancel";
import route98 from "./routes/v1/hunyuan3d/download";
import route99 from "./routes/v1/hunyuan3d/image-to-3d";
import route100 from "./routes/v1/hunyuan3d/status";
import route101 from "./routes/v1/iteration/index";
import route102 from "./routes/v1/lora-train/index";
import route103 from "./routes/v1/pipeline/callback/phase-complete";
import route104 from "./routes/v1/pipeline/callback/phase-progress";
import route105 from "./routes/v1/pipeline/callback/review-result";
import route106 from "./routes/v1/pipeline/ingest/images";
import route107 from "./routes/v1/pipeline/ingest/storyboard";
import route108 from "./routes/v1/pipeline/ingest/videos";
import route109 from "./routes/v1/pipeline/render-shot";
import route110 from "./routes/v1/pipeline/resume";
import route111 from "./routes/v1/pipeline/status/[taskId]";
import route112 from "./routes/v1/pipeline/submit-to-review";
import route113 from "./routes/v1/reflection/index";
import route114 from "./routes/v1/shots/from_graph";
import route115 from "./routes/v1/shots/list";
import route116 from "./routes/v1/skills/get";
import route117 from "./routes/v1/skills/list";
import route118 from "./routes/v1/skills/node-types";
import route119 from "./routes/v1/skills/phases";
import route120 from "./routes/v1/skills/register";
import route121 from "./routes/v1/snapshots/index";
import route122 from "./routes/v1/sync/batch";
import route123 from "./routes/v1/sync/pipeline-results";
import route124 from "./routes/v1/sync/pull/[projectId]";
import route125 from "./routes/v1/sync/status/[pipelineId]";
import route126 from "./routes/v1/telegram/webhook";
import route127 from "./routes/v1/trellis2/delete";
import route128 from "./routes/v1/trellis2/download";
import route129 from "./routes/v1/trellis2/image-to-3d";
import route130 from "./routes/v1/trellis2/preview";
import route131 from "./routes/v1/trellis2/status";
import route132 from "./routes/v1/tts/speak";
import route133 from "./routes/v1/tts/status";

export default async (app: Express) => {
  app.use("/api/assets/addAssets", route1);
  app.use("/api/assets/addAudioAssets", route2);
  app.use("/api/canvas/convert", route3);
  app.use("/api/canvas/execute", route4);
  app.use("/api/canvas/load", route5);
  app.use("/api/canvas/orchestrate", route6);
  app.use("/api/canvas/projectData", route7);
  app.use("/api/canvas/projects", route8);
  app.use("/api/canvas/review/approve", route9);
  app.use("/api/canvas/review/reject", route10);
  app.use("/api/canvas/review/score", route11);
  app.use("/api/canvas/save", route12);
  app.use("/api/canvas/storyboardPreview", route13);
  app.use("/api/canvas/v2/branches", route14);
  app.use("/api/canvas/v2/events", route15);
  app.use("/api/canvas/v2/file", route16);
  app.use("/api/canvas/v2/health", route17);
  app.use("/api/canvas/v2/import-from-dir", route18);
  app.use("/api/canvas/v2/layout", route19);
  app.use("/api/canvas/v2/links", route20);
  app.use("/api/canvas/v2/load-v2", route21);
  app.use("/api/canvas/v2/nodes", route22);
  app.use("/api/canvas/v2/review-gate", route23);
  app.use("/api/canvas/v2/save-v2", route24);
  app.use("/api/canvas/v2/thumbnail", route26);
  app.use("/api/canvas/v2/thumbnail/batch", route25);
  app.use("/api/production/flux/kontext-generate", route27);
  app.use("/api/production/flux/sceneGenerate", route28);
  app.use("/api/production/flux/status", route29);
  app.use("/api/production/indextts2/speak", route30);
  app.use("/api/production/indextts2/status", route31);
  app.use("/api/production/ltx/extension", route32);
  app.use("/api/production/ltx/fflf", route33);
  app.use("/api/production/ltx/msr", route34);
  app.use("/api/production/ltx/poseVideo", route35);
  app.use("/api/production/ltx/promptRelayI2V", route36);
  app.use("/api/production/ltx/singularityFFLF", route37);
  app.use("/api/production/ltx/trim", route38);
  app.use("/api/production/ltx/twoStageAudioI2V", route39);
  app.use("/api/production/postprocess/enhance", route40);
  app.use("/api/production/postprocess/status", route41);
  app.use("/api/production/qwenTts/speak", route42);
  app.use("/api/production/qwenTts/status", route43);
  app.use("/api/production/qwenTts/voiceId", route44);
  app.use("/api/production/storyboard/addStoryboard", route45);
  app.use("/api/production/wan21/scail2/status", route46);
  app.use("/api/production/wan21/scail2Replace", route47);
  app.use("/api/production/wan21/scail2Transfer", route48);
  app.use("/api/production/wan22/fflf", route49);
  app.use("/api/production/wan22/i2v", route50);
  app.use("/api/production/wan22/movetrack", route51);
  app.use("/api/production/wan22/t2v", route52);
  app.use("/api/project/addProject", route53);
  app.use("/api/project/delProject", route54);
  app.use("/api/project/editProject", route55);
  app.use("/api/project/getProject", route56);
  app.use("/api/proxy/goldTeam", route57);
  app.use("/api/proxy/reviewPlatform", route58);
  app.use("/api/script/addScript", route59);
  app.use("/api/setting/agentDeploy/agentSetKey", route60);
  app.use("/api/setting/agentDeploy/deployAgentModel", route61);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route62);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route63);
  app.use("/api/setting/agentDeploy/updateUseMode", route64);
  app.use("/api/setting/promptManage/getPrompt", route65);
  app.use("/api/setting/promptManage/updatePrompt", route66);
  app.use("/api/setting/skillManagement/getSkillContent", route67);
  app.use("/api/setting/skillManagement/getSkillList", route68);
  app.use("/api/setting/skillManagement/saveSkillContent", route69);
  app.use("/api/setting/vendorConfig/addVendor", route70);
  app.use("/api/setting/vendorConfig/addVendorModel", route71);
  app.use("/api/setting/vendorConfig/deleteVendor", route72);
  app.use("/api/setting/vendorConfig/delVendorModel", route73);
  app.use("/api/setting/vendorConfig/enableVendor", route74);
  app.use("/api/setting/vendorConfig/getCodeByLink", route75);
  app.use("/api/setting/vendorConfig/getVendorList", route76);
  app.use("/api/setting/vendorConfig/modelTest", route77);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route78);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route79);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route80);
  app.use("/api/setting/vendorConfig/updateCode", route81);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route82);
  app.use("/api/setting/vendorConfig/upVendorModel", route83);
  app.use("/api/v1/ace/cancel", route84);
  app.use("/api/v1/ace/comfyuiAnalyze", route85);
  app.use("/api/v1/ace/comfyuiDownload", route86);
  app.use("/api/v1/ace/comfyuiGenerate", route87);
  app.use("/api/v1/ace/generate", route88);
  app.use("/api/v1/ace/models", route89);
  app.use("/api/v1/ace/profiles", route90);
  app.use("/api/v1/ace/scheduler", route91);
  app.use("/api/v1/ace/status", route92);
  app.use("/api/v1/assets/from_node", route94);
  app.use("/api/v1/assets-registry", route93);
  app.use("/api/v1/audit", route95);
  app.use("/api/v1/feedback", route96);
  app.use("/api/v1/hunyuan3d/cancel", route97);
  app.use("/api/v1/hunyuan3d/download", route98);
  app.use("/api/v1/hunyuan3d/image-to-3d", route99);
  app.use("/api/v1/hunyuan3d/status", route100);
  app.use("/api/v1/iteration", route101);
  app.use("/api/v1/lora-train", route102);
  app.use("/api/v1/pipeline/callback/phase-complete", route103);
  app.use("/api/v1/pipeline/callback/phase-progress", route104);
  app.use("/api/v1/pipeline/callback/review-result", route105);
  app.use("/api/v1/pipeline/ingest/images", route106);
  app.use("/api/v1/pipeline/ingest/storyboard", route107);
  app.use("/api/v1/pipeline/ingest/videos", route108);
  app.use("/api/v1/pipeline/render-shot", route109);
  app.use("/api/v1/pipeline/resume", route110);
  app.use("/api/v1/pipeline/status/:taskId", route111);
  app.use("/api/v1/pipeline/submit-to-review", route112);
  app.use("/api/v1/reflection", route113);
  app.use("/api/v1/shots/from_graph", route114);
  app.use("/api/v1/shots/list", route115);
  app.use("/api/v1/skills", route117);
  app.use("/api/v1/skills/register", route120);
  app.use("/api/v1/skills/:skillId", route116);
  app.use("/api/v1/skills/:skillId", route118);
  app.use("/api/v1/skills/:skillId", route119);
  app.use("/api/v1/snapshots", route121);
  app.use("/api/v1/sync/batch", route122);
  app.use("/api/v1/sync/pipeline-results", route123);
  app.use("/api/v1/sync/pull/:projectId", route124);
  app.use("/api/v1/sync/status/:pipelineId", route125);
  app.use("/api/v1/telegram/webhook", route126);
  app.use("/api/v1/trellis2/delete", route127);
  app.use("/api/v1/trellis2/download", route128);
  app.use("/api/v1/trellis2/image-to-3d", route129);
  app.use("/api/v1/trellis2/preview", route130);
  app.use("/api/v1/trellis2/status", route131);
  app.use("/api/v1/tts/speak", route132);
  app.use("/api/v1/tts/status", route133);
}
