// @routes-hash 4f0fc6079decb66c3a1d1c23344c044e
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/addAudioAssets";
import route3 from "./routes/canvas/convert";
import route4 from "./routes/canvas/execute";
import route5 from "./routes/canvas/load";
import route6 from "./routes/canvas/orchestrate";
import route7 from "./routes/canvas/projectData";
import route8 from "./routes/canvas/projects";
import route9 from "./routes/canvas/review/approve";
import route10 from "./routes/canvas/review/reject";
import route11 from "./routes/canvas/review/score";
import route12 from "./routes/canvas/storyboardPreview";
import route13 from "./routes/canvas/v2/branches";
import route14 from "./routes/canvas/v2/events";
import route15 from "./routes/canvas/v2/file";
import route16 from "./routes/canvas/v2/g15-ops";
import route17 from "./routes/canvas/v2/gate-ops";
import route18 from "./routes/canvas/v2/gate-state";
import route19 from "./routes/canvas/v2/generation-config";
import route20 from "./routes/canvas/v2/health";
import route21 from "./routes/canvas/v2/import-from-dir";
import route22 from "./routes/canvas/v2/layout";
import route23 from "./routes/canvas/v2/links";
import route24 from "./routes/canvas/v2/load-v2";
import route25 from "./routes/canvas/v2/nodes";
import route26 from "./routes/canvas/v2/review-gate";
import route27 from "./routes/canvas/v2/save-v2";
import route28 from "./routes/canvas/v2/select-winner";
import route29 from "./routes/canvas/v2/sync-assets";
import route30 from "./routes/canvas/v2/thumbnail/batch";
import route31 from "./routes/canvas/v2/thumbnail/index";
import route32 from "./routes/notion-proxy";
import route33 from "./routes/production/ear/index";
import route34 from "./routes/production/flux/flux2Generate";
import route35 from "./routes/production/flux/kontext-generate/index";
import route36 from "./routes/production/flux/sceneGenerate";
import route37 from "./routes/production/flux/status";
import route38 from "./routes/production/gpu-queue/index";
import route39 from "./routes/production/indextts2/speak";
import route40 from "./routes/production/indextts2/status";
import route41 from "./routes/production/indextts2/voice-design";
import route42 from "./routes/production/llm/index";
import route43 from "./routes/production/ltx/extension";
import route44 from "./routes/production/ltx/fflf";
import route45 from "./routes/production/ltx/msr";
import route46 from "./routes/production/ltx/poseVideo";
import route47 from "./routes/production/ltx/promptRelayI2V";
import route48 from "./routes/production/ltx/singularityFFLF";
import route49 from "./routes/production/ltx/trim";
import route50 from "./routes/production/ltx/twoStageAudioI2V";
import route51 from "./routes/production/m3/generate";
import route52 from "./routes/production/m3/status";
import route53 from "./routes/production/mage/index";
import route54 from "./routes/production/minimax-h3/generate";
import route55 from "./routes/production/minimax-h3/i2va";
import route56 from "./routes/production/minimax-h3/ref2va";
import route57 from "./routes/production/minimax-h3/replace-audio";
import route58 from "./routes/production/minimax-h3/status";
import route59 from "./routes/production/minimax-h3/t2va";
import route60 from "./routes/production/minimax-h3/workflows";
import route61 from "./routes/production/music3/generate";
import route62 from "./routes/production/music3/status";
import route63 from "./routes/production/postprocess/enhance";
import route64 from "./routes/production/postprocess/rtx-vsr/index";
import route65 from "./routes/production/postprocess/seedvr2";
import route66 from "./routes/production/postprocess/status";
import route67 from "./routes/production/qwenTts/speak";
import route68 from "./routes/production/qwenTts/status";
import route69 from "./routes/production/qwenTts/voiceId";
import route70 from "./routes/production/shot-analysis/index";
import route71 from "./routes/production/storyboard/addStoryboard";
import route72 from "./routes/production/wan21/scail2/status";
import route73 from "./routes/production/wan21/scail2Replace";
import route74 from "./routes/production/wan21/scail2Transfer";
import route75 from "./routes/production/wan22/fflf";
import route76 from "./routes/production/wan22/i2v";
import route77 from "./routes/production/wan22/movetrack";
import route78 from "./routes/production/wan22/t2v";
import route79 from "./routes/project/addProject";
import route80 from "./routes/project/delProject";
import route81 from "./routes/project/editProject";
import route82 from "./routes/project/getProject";
import route83 from "./routes/proxy/goldTeam";
import route84 from "./routes/proxy/reviewPlatform";
import route85 from "./routes/script/addScript";
import route86 from "./routes/setting/agentDeploy/agentSetKey";
import route87 from "./routes/setting/agentDeploy/deployAgentModel";
import route88 from "./routes/setting/agentDeploy/getAgentDeploy";
import route89 from "./routes/setting/agentDeploy/getAgentUseMode";
import route90 from "./routes/setting/agentDeploy/updateUseMode";
import route91 from "./routes/setting/promptManage/getPrompt";
import route92 from "./routes/setting/promptManage/updatePrompt";
import route93 from "./routes/setting/skillManagement/getSkillContent";
import route94 from "./routes/setting/skillManagement/getSkillList";
import route95 from "./routes/setting/skillManagement/saveSkillContent";
import route96 from "./routes/setting/vendorConfig/addVendor";
import route97 from "./routes/setting/vendorConfig/addVendorModel";
import route98 from "./routes/setting/vendorConfig/deleteVendor";
import route99 from "./routes/setting/vendorConfig/delVendorModel";
import route100 from "./routes/setting/vendorConfig/enableVendor";
import route101 from "./routes/setting/vendorConfig/getCodeByLink";
import route102 from "./routes/setting/vendorConfig/getVendorList";
import route103 from "./routes/setting/vendorConfig/modelTest";
import route104 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route105 from "./routes/setting/vendorConfig/modelTest/textTest";
import route106 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route107 from "./routes/setting/vendorConfig/updateCode";
import route108 from "./routes/setting/vendorConfig/updateVendorInputs";
import route109 from "./routes/setting/vendorConfig/upVendorModel";
import route110 from "./routes/v1/ace/cancel";
import route111 from "./routes/v1/ace/comfyuiAnalyze";
import route112 from "./routes/v1/ace/comfyuiDownload";
import route113 from "./routes/v1/ace/comfyuiGenerate";
import route114 from "./routes/v1/ace/generate";
import route115 from "./routes/v1/ace/models";
import route116 from "./routes/v1/ace/profiles";
import route117 from "./routes/v1/ace/scheduler";
import route118 from "./routes/v1/ace/status";
import route119 from "./routes/v1/assets-registry/index";
import route120 from "./routes/v1/assets/from_node";
import route121 from "./routes/v1/audit/index";
import route122 from "./routes/v1/cinema/categories";
import route123 from "./routes/v1/cinema/list";
import route124 from "./routes/v1/cinema/query";
import route125 from "./routes/v1/cinema/seed";
import route126 from "./routes/v1/cinema/usage";
import route127 from "./routes/v1/director-desk/capabilities";
import route128 from "./routes/v1/director-desk/render";
import route129 from "./routes/v1/director-desk/scene";
import route130 from "./routes/v1/feedback/index";
import route131 from "./routes/v1/hunyuan3d/cancel";
import route132 from "./routes/v1/hunyuan3d/download";
import route133 from "./routes/v1/hunyuan3d/image-to-3d";
import route134 from "./routes/v1/hunyuan3d/status";
import route135 from "./routes/v1/iteration/index";
import route136 from "./routes/v1/lora-train/index";
import route137 from "./routes/v1/pipeline/callback/phase-complete";
import route138 from "./routes/v1/pipeline/callback/phase-progress";
import route139 from "./routes/v1/pipeline/callback/review-result";
import route140 from "./routes/v1/pipeline/ingest/images";
import route141 from "./routes/v1/pipeline/ingest/storyboard";
import route142 from "./routes/v1/pipeline/ingest/videos";
import route143 from "./routes/v1/pipeline/render-shot";
import route144 from "./routes/v1/pipeline/resume";
import route145 from "./routes/v1/pipeline/status/[taskId]";
import route146 from "./routes/v1/pipeline/submit-to-review";
import route147 from "./routes/v1/reflection/index";
import route148 from "./routes/v1/shots/from_graph";
import route149 from "./routes/v1/shots/list";
import route150 from "./routes/v1/skills/get";
import route151 from "./routes/v1/skills/list";
import route152 from "./routes/v1/skills/node-types";
import route153 from "./routes/v1/skills/phases";
import route154 from "./routes/v1/skills/register";
import route155 from "./routes/v1/snapshots/index";
import route156 from "./routes/v1/stableaudio/generate";
import route157 from "./routes/v1/stableaudio/inpaint";
import route158 from "./routes/v1/stableaudio/models";
import route159 from "./routes/v1/stableaudio/transform";
import route160 from "./routes/v1/storyboard/index";
import route161 from "./routes/v1/sync/batch";
import route162 from "./routes/v1/sync/pipeline-results";
import route163 from "./routes/v1/sync/pull/[projectId]";
import route164 from "./routes/v1/sync/status/[pipelineId]";
import route165 from "./routes/v1/telegram/webhook";
import route166 from "./routes/v1/trellis2/delete";
import route167 from "./routes/v1/trellis2/download";
import route168 from "./routes/v1/trellis2/image-to-3d";
import route169 from "./routes/v1/trellis2/preview";
import route170 from "./routes/v1/trellis2/status";
import route171 from "./routes/v1/tts/health";
import route172 from "./routes/v1/tts/speak";
import route173 from "./routes/v1/tts/status";
// 08-25 配置 Tab:GLM 模型配置(文件面 data/config/model-config.json)
import route174 from "./routes/canvas/v2/model-config";

export default async (app: Express) => {
  app.use("/api/assets/addAssets", route1);
  app.use("/api/assets/addAudioAssets", route2);
  app.use("/api/canvas/convert", route3);
  app.use("/api/canvas/execute", route4);
  app.use("/api/canvas/load", route5);
  app.use("/api/canvas/orchestrate", route6);
  app.use("/api/canvas/projectData", route7);
  app.use("/api/canvas/projects", route8);
  app.use("/api/canvas/review/approve", route9);
  app.use("/api/canvas/review/reject", route10);
  app.use("/api/canvas/review/score", route11);
  app.use("/api/canvas/storyboardPreview", route12);
  app.use("/api/canvas/v2/branches", route13);
  app.use("/api/canvas/v2/events", route14);
  app.use("/api/canvas/v2/file", route15);
  app.use("/api/canvas/v2/g15-ops", route16);
  app.use("/api/canvas/v2/gate-ops", route17);
  app.use("/api/canvas/v2/gate-state", route18);
  app.use("/api/canvas/v2/generation-config", route19);
  app.use("/api/canvas/v2/health", route20);
  app.use("/api/canvas/v2/import-from-dir", route21);
  app.use("/api/canvas/v2/layout", route22);
  app.use("/api/canvas/v2/links", route23);
  app.use("/api/canvas/v2/load-v2", route24);
  app.use("/api/canvas/v2/nodes", route25);
  app.use("/api/canvas/v2/review-gate", route26);
  app.use("/api/canvas/v2/save-v2", route27);
  app.use("/api/canvas/v2/select-winner", route28);
  app.use("/api/canvas/v2/sync-assets", route29);
  app.use("/api/canvas/v2/thumbnail", route31);
  app.use("/api/canvas/v2/thumbnail/batch", route30);
  app.use("/api/notion-proxy", route32);
  app.use("/api/production/ear", route33);
  app.use("/api/production/flux/flux2Generate", route34);
  app.use("/api/production/flux/kontext-generate", route35);
  app.use("/api/production/flux/sceneGenerate", route36);
  app.use("/api/production/flux/status", route37);
  app.use("/api/production/gpu-queue", route38);
  app.use("/api/production/indextts2/speak", route39);
  app.use("/api/production/indextts2/status", route40);
  app.use("/api/production/indextts2/voice-design", route41);
  app.use("/api/production/llm", route42);
  app.use("/api/production/ltx/extension", route43);
  app.use("/api/production/ltx/fflf", route44);
  app.use("/api/production/ltx/msr", route45);
  app.use("/api/production/ltx/poseVideo", route46);
  app.use("/api/production/ltx/promptRelayI2V", route47);
  app.use("/api/production/ltx/singularityFFLF", route48);
  app.use("/api/production/ltx/trim", route49);
  app.use("/api/production/ltx/twoStageAudioI2V", route50);
  app.use("/api/production/m3/generate", route51);
  app.use("/api/production/m3/status", route52);
  app.use("/api/production/mage", route53);
  app.use("/api/production/minimax-h3/generate", route54);
  app.use("/api/production/minimax-h3/i2va", route55);
  app.use("/api/production/minimax-h3/ref2va", route56);
  app.use("/api/production/minimax-h3/replace-audio", route57);
  app.use("/api/production/minimax-h3/status", route58);
  app.use("/api/production/minimax-h3/t2va", route59);
  app.use("/api/production/minimax-h3/workflows", route60);
  app.use("/api/production/music3/generate", route61);
  app.use("/api/production/music3/status", route62);
  app.use("/api/production/postprocess/enhance", route63);
  app.use("/api/production/postprocess/rtx-vsr", route64);
  app.use("/api/production/postprocess/seedvr2", route65);
  app.use("/api/production/postprocess/status", route66);
  app.use("/api/production/qwenTts/speak", route67);
  app.use("/api/production/qwenTts/status", route68);
  app.use("/api/production/qwenTts/voiceId", route69);
  app.use("/api/production/shot-analysis", route70);
  app.use("/api/production/storyboard/addStoryboard", route71);
  app.use("/api/production/wan21/scail2/status", route72);
  app.use("/api/production/wan21/scail2Replace", route73);
  app.use("/api/production/wan21/scail2Transfer", route74);
  app.use("/api/production/wan22/fflf", route75);
  app.use("/api/production/wan22/i2v", route76);
  app.use("/api/production/wan22/movetrack", route77);
  app.use("/api/production/wan22/t2v", route78);
  app.use("/api/project/addProject", route79);
  app.use("/api/project/delProject", route80);
  app.use("/api/project/editProject", route81);
  app.use("/api/project/getProject", route82);
  app.use("/api/proxy/goldTeam", route83);
  app.use("/api/proxy/reviewPlatform", route84);
  app.use("/api/script/addScript", route85);
  app.use("/api/setting/agentDeploy/agentSetKey", route86);
  app.use("/api/setting/agentDeploy/deployAgentModel", route87);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route88);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route89);
  app.use("/api/setting/agentDeploy/updateUseMode", route90);
  app.use("/api/setting/promptManage/getPrompt", route91);
  app.use("/api/setting/promptManage/updatePrompt", route92);
  app.use("/api/setting/skillManagement/getSkillContent", route93);
  app.use("/api/setting/skillManagement/getSkillList", route94);
  app.use("/api/setting/skillManagement/saveSkillContent", route95);
  app.use("/api/setting/vendorConfig/addVendor", route96);
  app.use("/api/setting/vendorConfig/addVendorModel", route97);
  app.use("/api/setting/vendorConfig/deleteVendor", route98);
  app.use("/api/setting/vendorConfig/delVendorModel", route99);
  app.use("/api/setting/vendorConfig/enableVendor", route100);
  app.use("/api/setting/vendorConfig/getCodeByLink", route101);
  app.use("/api/setting/vendorConfig/getVendorList", route102);
  app.use("/api/setting/vendorConfig/modelTest", route103);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route104);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route105);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route106);
  app.use("/api/setting/vendorConfig/updateCode", route107);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route108);
  app.use("/api/setting/vendorConfig/upVendorModel", route109);
  app.use("/api/v1/ace/cancel", route110);
  app.use("/api/v1/ace/comfyuiAnalyze", route111);
  app.use("/api/v1/ace/comfyuiDownload", route112);
  app.use("/api/v1/ace/comfyuiGenerate", route113);
  app.use("/api/v1/ace/generate", route114);
  app.use("/api/v1/ace/models", route115);
  app.use("/api/v1/ace/profiles", route116);
  app.use("/api/v1/ace/scheduler", route117);
  app.use("/api/v1/ace/status", route118);
  app.use("/api/v1/assets/from_node", route120);
  app.use("/api/v1/assets-registry", route119);
  app.use("/api/v1/audit", route121);
  app.use("/api/v1/cinema/categories", route122);
  app.use("/api/v1/cinema/list", route123);
  app.use("/api/v1/cinema/query", route124);
  app.use("/api/v1/cinema/seed", route125);
  app.use("/api/v1/cinema/usage", route126);
  app.use("/api/v1/director-desk/capabilities", route127);
  app.use("/api/v1/director-desk/render", route128);
  app.use("/api/v1/director-desk/scene", route129);
  app.use("/api/v1/feedback", route130);
  app.use("/api/v1/hunyuan3d/cancel", route131);
  app.use("/api/v1/hunyuan3d/download", route132);
  app.use("/api/v1/hunyuan3d/image-to-3d", route133);
  app.use("/api/v1/hunyuan3d/status", route134);
  app.use("/api/v1/iteration", route135);
  app.use("/api/v1/lora-train", route136);
  app.use("/api/v1/pipeline/callback/phase-complete", route137);
  app.use("/api/v1/pipeline/callback/phase-progress", route138);
  app.use("/api/v1/pipeline/callback/review-result", route139);
  app.use("/api/v1/pipeline/ingest/images", route140);
  app.use("/api/v1/pipeline/ingest/storyboard", route141);
  app.use("/api/v1/pipeline/ingest/videos", route142);
  app.use("/api/v1/pipeline/render-shot", route143);
  app.use("/api/v1/pipeline/resume", route144);
  app.use("/api/v1/pipeline/status/:taskId", route145);
  app.use("/api/v1/pipeline/submit-to-review", route146);
  app.use("/api/v1/reflection", route147);
  app.use("/api/v1/shots/from_graph", route148);
  app.use("/api/v1/shots/list", route149);
  app.use("/api/v1/skills", route151);
  app.use("/api/v1/skills/register", route154);
  app.use("/api/v1/skills/:skillId", route150);
  app.use("/api/v1/skills/:skillId", route152);
  app.use("/api/v1/skills/:skillId", route153);
  app.use("/api/v1/snapshots", route155);
  app.use("/api/v1/stableaudio/generate", route156);
  app.use("/api/v1/stableaudio/inpaint", route157);
  app.use("/api/v1/stableaudio/models", route158);
  app.use("/api/v1/stableaudio/transform", route159);
  app.use("/api/v1/storyboard", route160);
  app.use("/api/v1/sync/batch", route161);
  app.use("/api/v1/sync/pipeline-results", route162);
  app.use("/api/v1/sync/pull/:projectId", route163);
  app.use("/api/v1/sync/status/:pipelineId", route164);
  app.use("/api/v1/telegram/webhook", route165);
  app.use("/api/v1/trellis2/delete", route166);
  app.use("/api/v1/trellis2/download", route167);
  app.use("/api/v1/trellis2/image-to-3d", route168);
  app.use("/api/v1/trellis2/preview", route169);
  app.use("/api/v1/trellis2/status", route170);
  app.use("/api/v1/tts/health", route171);
  app.use("/api/v1/tts/speak", route172);
  app.use("/api/v1/tts/status", route173);
  app.use("/api/canvas/v2/model-config", route174);
}
