// @routes-hash 72a19d0a42620de7690a4335be827821
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/delAssets";
import route3 from "./routes/assets/generateAssets";
import route4 from "./routes/assets/getAssets";
import route5 from "./routes/assets/getImage";
import route6 from "./routes/assets/getStoryboard";
import route7 from "./routes/assets/polishPrompt";
import route8 from "./routes/assets/saveAssets";
import route9 from "./routes/assets/updateAssets";
import route10 from "./routes/index/index";
import route11 from "./routes/novel/addNovel";
import route12 from "./routes/novel/delNovel";
import route13 from "./routes/novel/getNovel";
import route14 from "./routes/novel/updateNovel";
import route15 from "./routes/other/clearDatabase";
import route16 from "./routes/other/deleteAllData";
import route17 from "./routes/other/getCaptcha";
import route18 from "./routes/other/login";
import route19 from "./routes/outline/addOutline";
import route20 from "./routes/outline/agentsOutline";
import route21 from "./routes/outline/delOutline";
import route22 from "./routes/outline/getHistory";
import route23 from "./routes/outline/getOutline";
import route24 from "./routes/outline/getPartScript";
import route25 from "./routes/outline/getStoryline";
import route26 from "./routes/outline/setHistory";
import route27 from "./routes/outline/updateOutline";
import route28 from "./routes/outline/updateScript";
import route29 from "./routes/outline/updateStoryline";
import route30 from "./routes/project/addProject";
import route31 from "./routes/project/delProject";
import route32 from "./routes/project/getProject";
import route33 from "./routes/project/getProjectCount";
import route34 from "./routes/project/getSingleProject";
import route35 from "./routes/project/updateProject";
import route36 from "./routes/prompt/getPrompts";
import route37 from "./routes/prompt/updatePrompt";
import route38 from "./routes/script/generateScriptApi";
import route39 from "./routes/script/generateScriptSave";
import route40 from "./routes/script/geScriptApi";
import route41 from "./routes/setting/getSetting";
import route42 from "./routes/setting/updateSetting";
import route43 from "./routes/storyboard/batchSuperScoreImage";
import route44 from "./routes/storyboard/chatStoryboard";
import route45 from "./routes/storyboard/generateShotImage";
import route46 from "./routes/storyboard/generateStoryboardApi";
import route47 from "./routes/storyboard/generateVideoPrompt";
import route48 from "./routes/storyboard/getStoryboard";
import route49 from "./routes/storyboard/keepStoryboard";
import route50 from "./routes/storyboard/saveStoryboard";
import route51 from "./routes/storyboard/uploadImage";
import route52 from "./routes/task/getTaskApi";
import route53 from "./routes/task/taskDetails";
import route54 from "./routes/user/getUser";
import route55 from "./routes/video/addVideo";
import route56 from "./routes/video/addVideoConfig";
import route57 from "./routes/video/deleteVideoConfig";
import route58 from "./routes/video/generatePrompt";
import route59 from "./routes/video/generateVideo";
import route60 from "./routes/video/getManufacturer";
import route61 from "./routes/video/getVideo";
import route62 from "./routes/video/getVideoConfigs";
import route63 from "./routes/video/getVideoModel";
import route64 from "./routes/video/getVideoStoryboards";
import route65 from "./routes/video/reviseVideoStoryboards";
import route66 from "./routes/video/saveVideo";
import route67 from "./routes/video/upDateVideoConfig";

export default async (app: Express) => {
  app.use("/assets/addAssets", route1);
  app.use("/assets/delAssets", route2);
  app.use("/assets/generateAssets", route3);
  app.use("/assets/getAssets", route4);
  app.use("/assets/getImage", route5);
  app.use("/assets/getStoryboard", route6);
  app.use("/assets/polishPrompt", route7);
  app.use("/assets/saveAssets", route8);
  app.use("/assets/updateAssets", route9);
  app.use("/index", route10);
  app.use("/novel/addNovel", route11);
  app.use("/novel/delNovel", route12);
  app.use("/novel/getNovel", route13);
  app.use("/novel/updateNovel", route14);
  app.use("/other/clearDatabase", route15);
  app.use("/other/deleteAllData", route16);
  app.use("/other/getCaptcha", route17);
  app.use("/other/login", route18);
  app.use("/outline/addOutline", route19);
  app.use("/outline/agentsOutline", route20);
  app.use("/outline/delOutline", route21);
  app.use("/outline/getHistory", route22);
  app.use("/outline/getOutline", route23);
  app.use("/outline/getPartScript", route24);
  app.use("/outline/getStoryline", route25);
  app.use("/outline/setHistory", route26);
  app.use("/outline/updateOutline", route27);
  app.use("/outline/updateScript", route28);
  app.use("/outline/updateStoryline", route29);
  app.use("/project/addProject", route30);
  app.use("/project/delProject", route31);
  app.use("/project/getProject", route32);
  app.use("/project/getProjectCount", route33);
  app.use("/project/getSingleProject", route34);
  app.use("/project/updateProject", route35);
  app.use("/prompt/getPrompts", route36);
  app.use("/prompt/updatePrompt", route37);
  app.use("/script/generateScriptApi", route38);
  app.use("/script/generateScriptSave", route39);
  app.use("/script/geScriptApi", route40);
  app.use("/setting/getSetting", route41);
  app.use("/setting/updateSetting", route42);
  app.use("/storyboard/batchSuperScoreImage", route43);
  app.use("/storyboard/chatStoryboard", route44);
  app.use("/storyboard/generateShotImage", route45);
  app.use("/storyboard/generateStoryboardApi", route46);
  app.use("/storyboard/generateVideoPrompt", route47);
  app.use("/storyboard/getStoryboard", route48);
  app.use("/storyboard/keepStoryboard", route49);
  app.use("/storyboard/saveStoryboard", route50);
  app.use("/storyboard/uploadImage", route51);
  app.use("/task/getTaskApi", route52);
  app.use("/task/taskDetails", route53);
  app.use("/user/getUser", route54);
  app.use("/video/addVideo", route55);
  app.use("/video/addVideoConfig", route56);
  app.use("/video/deleteVideoConfig", route57);
  app.use("/video/generatePrompt", route58);
  app.use("/video/generateVideo", route59);
  app.use("/video/getManufacturer", route60);
  app.use("/video/getVideo", route61);
  app.use("/video/getVideoConfigs", route62);
  app.use("/video/getVideoModel", route63);
  app.use("/video/getVideoStoryboards", route64);
  app.use("/video/reviseVideoStoryboards", route65);
  app.use("/video/saveVideo", route66);
  app.use("/video/upDateVideoConfig", route67);
}
